tnefparse/tnef.py

File "/tnefparse/tnef.py", line 255, in to_zip
root, ext = os.path.splitext(filename)
NameError: global name 'os' is not defined

missing import os

---

tnefparse/tnef.py

It's bad practice to call sys.exit() from a library.

s/sys.exit()/raise ValueError/.

---

tnefparse/__init__.py

This is not a method, so `self` is no needed.

Remove self

---

tnefparse/mapi.py

Instantiating a new logger is not required and causes issues when using as a python module since logs will be generated twice

Remove basicLogger singleton

---

tnefparse/mapi.py
tnefparse/tnef.py

The inlining of bytes_to_int in decode_mapi used the py2 version, not py3. I've switched it to use a struct based method which is both fast and supported by both py2 and py3. 
We should consider using struct more broadly, but it requires the integer size to be known in advance to be fast. We could have separate functions for each byte -> int sizes.

Fix inline bytes_to_int for py3

---

tests/test_cmdline.py
tests/test_decoding.py
tnefparse/__init__.py
tnefparse/cmdline.py
tnefparse/mapi.py
tnefparse/tnef.py
tnefparse/util.py

Standardize on 4-space indents and unix line endings.
There are no code changes in this PR, only changes to whitespace. I used `dos2unix`, `isort` and `black` to clean things up, then hand-tuned to restore some of the layout we already had.

Cleanup whitespace including line-endings

---

tnefparse/mapi.py

The uint* functions already know how many bytes they they need, so this saves us from doing a copy of the those bytes before converting them to ints.

Minor code cleanup

---

README.rst
tests/test_cmdline.py
tests/test_decoding.py
tnefparse/cmdline.py
tnefparse/codepage.py
tnefparse/mapi.py
tnefparse/tnef.py

- Bugfix: GUID property names are returned in `__str__`
- Reconcile object and mapi level properties
- strip trailing `\0` from object level attribute strings
- Bugfix: prevent recursive addtion of recipient list due to variable name overlap
- Decode binary body and filenames if we can
- Add a dump method

Decode body strings if we have mapi codepage values

---

tnefparse/tnef.py

Hello,
First of all, thank you for your work, this module is really useful to me !
I noticed that TNEF objects representing the end time of an event where not parsed into datetimes in the TNEF constructor.
I figured this was a slight oversight and added `TNEF.ATTDATEEND` to the list of TNEFObject.name readable as datetimes [here](https://github.com/koodaamo/tnefparse/blob/master/tnefparse/tnef.py#L311)
I hope this helps,
Evomassiny

Parse `TNEF.ATTDATEEND` objects into datetimes

---

.github/workflows/pythonpackage.yml
.travis.yml
HISTORY.rst
README.rst
setup.py
tox.ini

As `python setup.py test` is deprecated, tests are now run by tox and pytest.
https://setuptools.readthedocs.io/en/latest/setuptools.html#test-build-package-and-run-a-unittest-suite
While using the deprecated `test` command, the optional dependency `compressed_rtf` was provided via `tests_require`, which accompanied the mentioned `test` command.
As we now use pytest/tox, the additional requirements are provided via the `extras_require` keyword, which also offers the additional benefit that the users of the package can install the extras via `pip install tnefparse[optional]`.
if this PR gets accepted, it would be nice to document that optional installation method in the README).
The `how to run tests` section in the README.rst was updated to reflect the changes.
Also, now you can generate …

Modernize package and test setup

---

README.rst

Also, use PyPi version badge from shields.io, as it it looks a tad better and sharper than the old one.
I generated a preview via `zest.releaser`s `longtest` command - if there is a simpler way - I am always looking forward to learn new things.

Add badge for supported Python versions

---

.travis.yml

pytest 4.3.1 is installed, but pytest-cov recently started to require
pytest >= 4.6.
modified:   .travis.yml

Fix broken Travis build

---

tests/test_cmdline.py
tnefparse/cmdline.py

In an uncovered path exc.message was used, which is Python 2 only syntax.
This has been updated.
As a suitable TNEF file is missing, the test makes heavy usage of mock.
If a suitable test file can be found, the test should be rewritten.
This fixes #82 
modified:   tests/test_cmdline.py
modified:   tnefparse/cmdline.py

Fix exception handling when TNEF raises a ValueError

---

tnefparse/mapi.py

Call `logging.exception` method to get the custom message and stack trace in one call.

Log exception's stack properly

---

tnefparse/cmdline.py
tnefparse/mapi.py
tnefparse/tnef.py
tnefparse/util.py

Replaced all `'hello %s' % world` and `f'hello {world}'` syntax with the old standard lazy `'hello %s', world`.

Use % formatting in log messages

---

HISTORY.rst
tnefparse/cmdline.py
tnefparse/codepage.py
tnefparse/tnef.py
tox.ini

You can run the type checker with `tox -e mypy`.
This is just a start.
- A lot of type annotations are still missing.
- The type checker is not yet using the strict option.
- Type annotations are not yet enforced in CI.
modified:   tnefparse/cmdline.py
modified:   tnefparse/codepage.py
modified:   tnefparse/tnef.py
modified:   tox.ini
P.S.: As there is quite some development going on, and as typing the complete project will take quite some time (at least for me), I suggest to merge this soon, as otherwise a lot of merge conflicts could arise. Python offers the concept of gradual typing, so, why no use it?

Introduce type annotations

---

tests/test_cmdline.py

- Add test for printing help when cli is called with no args
- Add test for the overview cli option
This is one PR (of many) to get test coverage to 100%, see #92

Add tests for cmdline.py

---

HISTORY.rst
tests/test_tnef.py
tnefparse/tnef.py

This fixes #94 
new file:   tests/test_tnef.py
modified:   tnefparse/tnef.py

Fix str representation of TNEF

---

HISTORY.rst
README.rst
tests/test_cmdline.py
tests/test_decoding.py
tnefparse/cmdline.py
tnefparse/tnef.py

Fixed the [bad commit from a poorly-reviewed PR in 2019](https://github.com/koodaamo/tnefparse/pull/54/commits/d9f7e6477ebff3a4b999af1bf3ab5a2457cc6679) by copying over the contributed feature code manually, and adding just what's needed to satisfy checks.
~~Need to merge #81 after this.~~

put cmd-line attch zip generation support where it belongs

---

HISTORY.rst
tests/test_cmdline.py
tnefparse/cmdline.py

Replace eval by getattr

---

HISTORY.rst
tests/test_decoding.py

I've updated the test `test_zip` in `test_decoding.py` to create TNEF object to avoid the deprecation warning.

Fix for deprecation warning #98

---

.github/workflows/pythonpackage.yml
HISTORY.rst

This adds triggers to the GitHub Actions CI when:
1. push (like until now)
2. pull request, so it helps you to review PR and might replace Travis completely 
3. once a week (deliberately chosen next night, but feel free to set any other time) to get information on broken dependency even when there's no activity on the repo
4. on demand, as a special “rerun” button appears on the Actions page

Run GHA CI for pull requests, once a week and on demand as well

---

tests/test_decoding.py
tnefparse/cmdline.py
tnefparse/mapi.py
tnefparse/tnef.py
tnefparse/util.py

1. `log.warn` is deprecated, use `log.warning` instead
2. `"""docstrings need triple double quotes"""`
3. convert some variable names to lowercase
4. convert the last `%` strings to f-strings

Fix tiny Python3 bits

---

tnefparse/tnef.py

Attached messages may have no file name.  In this case, set the
name to 'unlabeled_attachment.bin' so it visible in the listing
(option '-o') and can be extracted ('-a', '-z').  See also issue
koodaamo/tnefparse#74.
Signed-off-by: Albrecht Dreß <albrecht.dress@arcor.de>

ensure attachment file name

---

tnefparse/tnef.py

Solve "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 0: invalid start byte"

Solve "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 ..."

---

tnefparse/tnef.py

Reverts koodaamo/tnefparse#122
The reverted PR will cause issues when codepage is not set, since `None` is not acceptable value for `bytes.decode`.

Revert "Solve "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 ...""
